const processSteps = [
  ['01', 'Empathize', 'Stakeholder interviews and user research to understand the real user, not an assumption.'],
  ['02', 'Define', 'Journey map, problem tree, value proposition canvas to find the real problem.'],
  ['03', 'Ideate', 'BRD, user stories, acceptance criteria, prioritization to turn the problem into buildable requirements.'],
  ['04', 'Prototype', 'Lo-fi to hi-fi, each fidelity answering a different question, fast and cheap before building for real.'],
  ['05', 'Test', 'Usability testing and UAT, feeding evidence and defects back into the loop.'],
];
const journey = [['Minute 0–3','Watches a lesson and hears a key idea','Excited','Insight is easy to lose while playback continues'],['Minute 3–10','Tries to write a quick note','Interrupted','Switching tools breaks concentration'],['Later review','Returns to the video to study','Frustrated','Cannot locate the exact moment behind a note'],['Sharing','Discusses with classmates','Careful','Public comments feel noisy or too exposed'],['Exam prep','Turns notes into learning material','Relieved','Private timestamped notes make review faster']];
const stories = [['BR1','As a learner, I want to add a private note at the current timestamp so I can save context without leaving the video.','Note is saved with video ID, timestamp, text, and owner.'],['BR2','As a learner, I want to jump from a note back to its timestamp so I can review evidence quickly.','Clicking a note resumes playback within one second of the saved time.'],['BR3','As a learner, I want to edit and delete notes so my study material stays accurate.','Owner can update or remove notes with confirmation for delete.'],['BR4','As a learner, I want notes to stay private by default so I can write honestly.','No other user can view private notes.'],['BR5','As a product team, we want traceable requirements so releases stay testable.','Every core requirement maps to at least one UAT scenario.']];
const rtm = [['BR1','UAT1','Passed'],['BR2','UAT2','In test'],['BR3','UAT2','Passed'],['BR4','UAT3','Backlog'],['BR5','UAT1–UAT3','Passed']];
const projects = [['VPL Asset Tokenizer','3–5/2026','Asset digitization solution with BMC, value proposition, 3-pillar feasibility assessment, and AI-assisted market synthesis.'],['Ride','10–12/2025','Motorbike roadside rescue platform with multi-tier dispatch flow, 30s response / 60s contact SLA, BRD, and technical flow.'],['Web-based AR Navigation','3–5/2025','Mall AR wayfinding research with 20+ users, journey map, storyboard, and usability testing where 80% found it effective.'],['FUTA Smart Journey Ecosystem','1–3/2025','Digital service blueprint, AS-IS/gap analysis, TO-BE process, AI smart dispatching, and real-time tracking.']];
const rows = data => data.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('');
const badge = status => `<span class="badge ${status.toLowerCase().replace(' ', '-')}">${status}</span>`;

document.querySelector('#root').innerHTML = `
<header class="nav"><a href="#hero" class="brand">An · BA/UX</a><nav>${['Process','Canvas','Requirements','Testing','About','AI Team','Get in touch'].map(item => `<a href="#${item.toLowerCase().replaceAll(' ', '-')}">${item}</a>`).join('')}</nav></header>
<main>
<section id="hero" class="hero section"><div><p class="eyebrow">Product Discovery · UX Research · Business Analysis</p><h1>Nguyễn Thị Thúy An</h1><p class="tagline">I build empathy into systems, not just features.</p><div class="hero-actions"><a class="button primary" href="#canvas">See case study →</a><a class="button ghost" href="#ai-team">Talk to my AI 🤖</a></div></div><aside class="hero-card"><div class="icon">✦</div><h2>TimeNote</h2><p>A product-discovery case study turning learner frustration into timestamped private notes, testable requirements, and transparent UAT outcomes.</p></aside></section>
<section id="process" class="section"><p class="eyebrow">How I work</p><h2>Process</h2><div class="process-grid">${processSteps.map(([n,t,d]) => `<article class="step"><span>${n}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>
<section id="canvas" class="section split"><div><p class="eyebrow">TimeNote case study</p><h2>Canvas</h2><p class="lead">Learners need a way to capture video insights privately at the exact moment they happen, because public comments are noisy and external notes lose context.</p></div><div class="table-card"><h3>Journey map</h3><table><tbody>${rows(journey)}</tbody></table></div><div class="tree"><h3>Problem tree</h3><p><strong>Effects:</strong> lost insights, slower review, lower confidence.</p><p><strong>Core problem:</strong> notes are separated from video context.</p><p><strong>Root causes:</strong> tool switching, public-comment anxiety, weak traceability.</p></div><div class="tree"><h3>Value proposition</h3><p>Private timestamped notes help self-directed learners review faster, write honestly, and turn moments into reusable study assets.</p></div></section>
<section id="requirements" class="section"><p class="eyebrow">BRD · User stories · RTM</p><h2>Requirements</h2><div class="brd"><p><strong>Objective:</strong> Validate a lightweight private note layer for learning videos.</p><p><strong>Scope in:</strong> create, edit, delete, timestamp jump, privacy default, traceability.</p><p><strong>Scope out:</strong> public sharing, AI summaries, multi-video notebooks.</p><p><strong>Success metrics:</strong> note creation under 10 seconds, timestamp jump accuracy, UAT pass rate.</p></div><div class="table-card"><table><thead><tr><th>ID</th><th>User story</th><th>Acceptance criteria</th></tr></thead><tbody>${rows(stories)}</tbody></table></div></section>
<section id="testing" class="section split"><div><p class="eyebrow">Wireframe · UAT</p><h2>Testing</h2><p class="lead">Lo-fi wireframes focused on one question: can a learner capture a note without losing the video moment?</p></div><div class="wireframe"><div class="video">◉<br>Video player</div><div class="notes">Private notes panel<br><button>+ Add timestamp note</button></div></div><div class="table-card"><h3>RTM status</h3><table><tbody>${rtm.map(([br,uat,status]) => `<tr><td>${br}</td><td>${uat}</td><td>${badge(status)}</td></tr>`).join('')}</tbody></table></div><div class="tree"><h3>UAT scenarios</h3><p>✅ UAT1: Create a note while video is playing — pass.</p><p>✅ UAT2: Edit a note and jump back to timestamp — in test.</p><p><strong>UAT3:</strong> Verify privacy across accounts — fail case captured for backlog.</p></div></section>
<section id="about" class="section about"><p class="eyebrow">About</p><h2>Clarity from research to release</h2><p>My background is in Technology and Innovation with a focus on business analysis and UX research. I have run end-to-end projects for an asset-tokenization platform, a roadside rescue service, and a mall wayfinding experience validated with over 20 users.</p><p>What I care about is clarity. A good product removes friction the user never even notices. I bridge research and delivery: journeys and problem trees to find the friction, then BRDs, user stories, and UAT to take it away and keep ownership clear until release.</p><div class="project-grid">${projects.map(([name,date,desc]) => `<article class="project"><span>${date}</span><h3>${name}</h3><p>${desc}</p></article>`).join('')}</div></section>
<section id="ai-team" class="section ai"><p class="eyebrow">AI Team</p><h2>Interview me through my AI</h2><div class="chat"><span>🤖</span><p id="chat-text">Ask about An’s discovery process, TimeNote requirements, or UAT decisions.</p></div><div class="questions">${['Why did An choose private notes over public comments like Bilibili?','Which UAT case failed, and how did An handle it?','Which stage of the BA process is An strongest at?'].map(q => `<button>${q}</button>`).join('')}</div></section>
<section id="get-in-touch" class="section contact"><p class="eyebrow">Get in touch</p><h2>Let’s make useful systems feel human.</h2><div class="contact-actions"><a href="mailto:an@example.com">✉ Email</a><a href="tel:+84000000000">☎ Call</a><a href="https://maps.google.com/?q=Ho%20Chi%20Minh%20City">⌖ Ho Chi Minh City</a></div></section>
</main><footer class="toolkit"><strong>Toolkit</strong><span>Research & Discovery</span><span>BRD</span><span>User Stories</span><span>RTM</span><span>UAT</span><span>Figma</span><span>Jira</span><span>Miro</span><span>SQL</span></footer>`;

document.querySelectorAll('.questions button').forEach(button => button.addEventListener('click', () => {
  const question = button.textContent;
  document.querySelector('#chat-text').textContent = question.includes('failed') ? 'UAT3 exposed a privacy-edge case. An kept it transparent in the RTM, moved the fix to backlog, and protected release scope.' : question.includes('private') ? 'Private notes reduce performance pressure and noise. The product keeps reflection personal while preserving timestamp context.' : 'An is strongest where research becomes delivery: journey maps, problem trees, BRDs, user stories, RTM, and UAT ownership.';
}));
